import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contractsRoot = resolve(packageRoot, "../../contracts/out");
const outputPath = resolve(packageRoot, "src/abi/generated.ts");
const contracts = [
  "LaunchFactory",
  "TemplateRegistry",
  "PlatformConfig",
  "MintVault",
  "RewardVault",
  "BuybackVault",
  "FinanceVault",
  "LaunchLimits",
  "WhitelistMint",
  "FlapMintVault",
  "FlapAdapterV1",
];

function exportName(contractName) {
  return `${contractName[0].toLowerCase()}${contractName.slice(1)}Abi`;
}

const sections = [
  "// Generated by `pnpm protocol:abi`; do not edit by hand.",
  "",
];
for (const contractName of contracts) {
  const artifactPath = resolve(contractsRoot, `${contractName}.sol/${contractName}.json`);
  const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
  sections.push(`export const ${exportName(contractName)} = ${JSON.stringify(artifact.abi, null, 2)} as const;`, "");
}
const generated = `${sections.join("\n")}\n`;

if (process.argv.includes("--check")) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== generated) {
    console.error("Generated protocol ABI exports are stale. Run `pnpm protocol:abi`.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated);
}
